version: 2

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unconvert
    - unused
    - misspell
    - prealloc

linters-settings: {}

issues:
  exclude-use-default: false
