version: 2

project_name: spogo

changelog:
  disable: true

builds:
  - id: spogo
    main: ./cmd/spogo
    binary: spogo
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: spogo_darwin
    main: ./cmd/spogo
    binary: spogo
    env:
      - CGO_ENABLED=1
    targets:
      - darwin_amd64
      - darwin_arm64

archives:
  - builds:
      - spogo
      - spogo_darwin
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
